### ISSUE TITLE
About the lane to lane topology loss 

### ISSUE THREAD

**Issue by lizimo061** [wudongming97/TopoMLP#1]
In [topo_ll_head](https://github.com/wudongming97/TopoMLP/blob/master/projects/topomlp/models/heads/topo_ll_head.py#L157) part L157, are the `targets` and `rel_preds` equations wrong when batch size greater than 1, since the xs_new and ys_new are defined for the last batch?

**Comment by wudongming97** [comment]
Our code does not support batch size > 1.

**Comment by lizimo061** [comment]
It is said in the literature that experiments are using batch size of 8. Any plan for updating the code?

**Comment by wudongming97** [comment]
It means we use a batch size of 1 on each card. Using 8 cards refers to a batch size of 8.

**Comment by lizimo061** [comment]
Got it, thanks.

**Comment by Wolfybox** [comment]
> It means we use a batch size of 1 on each card. Using 8 cards refers to a batch size of 8.

@wudongming97  is it possible to extend it to support multi-batches by padding ?
