### ISSUE TITLE
Configs of other backbone

### ISSUE THREAD

**Issue by rongfu-dsb** [wudongming97/TopoMLP#17]
Hi, this is an excellent piece of work! 
Could you please provide the configuration files for using VOV and Swin-B? This would make it more convenient to explore the impact of other backbones on performance.

**Comment by wudongming97** [comment]
Okay. I will release these experiments this week. Please stay tuned.

**Comment by wudongming97** [comment]
We have updated the configuration files of VOV and Swin-B. If you find TopoMLP is useful in your research or applications, please consider giving us a star.
