### ISSUE TITLE
The discussion about the TOP_ll

### ISSUE THREAD

**Issue by zhangmanCN** [wudongming97/TopoMLP#2]
May I ask why the fifth result of prediction calculation before and after enhance prediction is 0.25 and 0.3 respectively.
![image](https://github.com/wudongming97/TopoMLP/assets/59424759/01823c7f-0ea6-4ba4-a296-8d5927f67821)
In my understanding, as shown in the follow formula(it is a part of formula about TOP_ll):
![image](https://github.com/wudongming97/TopoMLP/assets/59424759/d92ebd98-e9e2-4d3c-bf27-eede6fbaf58c)
 To the ith predict topology of a certain vertex, and if it is correct, the predict topology score should be j/i * 1, where j is the right number in the first i topology predict result. and j/i is the result of the P()，1 is the result of the indicator func.
Do I have any mistake? Please advise me.

**Comment by wudongming97** [comment]
Please refer to the code about how to calculate P() in OpenLane-V2:
https://github.com/OpenDriveLab/OpenLane-V2/blob/master/openlanev2/centerline/evaluation/evaluate.py#L331-L335

**Comment by wudongming97** [comment]
Sorry, we indeed made a mistake in the last row:  0.25 and 0.3. It should be 0.6 and 0.6.

**Comment by zhangmanCN** [comment]
Thank you for your reply. I think the 0.6 and 0.6 is right~
