### ISSUE TITLE
Why "is_detach" in topo_ll_head and topo_lt_head is True?

### ISSUE THREAD

**Issue by night3759** [wudongming97/TopoMLP#21]
If the "self.is_detach" is True, the MLP of topo_ll_head and topo_lt_head may not be trained. Do I understand right? Why detach?

**Comment by wudongming97** [comment]
The topology head is trained,  but its update would not influence the detection when using "self.is_detach". From my experiment, it doesn't matter if you use "self.is_detach".

**Comment by Wolfybox** [comment]
> The topology head is trained, but its update would not influence the detection when using "self.is_detach". From my experiment, it doesn't matter if you use "self.is_detach".

does "self.is_detach" option  prevent the gradients from bp to the upstream module?

**Comment by wudongming97** [comment]
yep.

**Comment by Wolfybox** [comment]
> yep.

Thanks .
