### ISSUE TITLE
Yolov8 proposals

### ISSUE THREAD

**Issue by KSonPham** [wudongming97/TopoMLP#26]
Hi,
Is it possible for you to release the yolov8 proposals file?
Best regards,
Pham

**Comment by wudongming97** [comment]
Yes. We will release YOLOv8 proposals, but it needs to be after the deadline of the 2nd OpenLane topology challenge.

**Comment by sugar-fly** [comment]
Hi,

Can you release the yolov8 proposal files now?

best,

**Comment by wudongming97** [comment]
We release the file.
https://drive.google.com/drive/folders/1sYmRAtcPvMU_yQCJZ4-vqCibM3WP8ygI?usp=drive_link
