### ISSUE TITLE
control points 4 or 11

### ISSUE THREAD

**Issue by Fightinging1997** [wudongming97/TopoMLP#27]
Hi, thanks for open-sourcing the code!

I don't quite understand the meaning of the following paragraph in the paper.

**LaneDetector**. The lane query number is set to NL=300, and the number of control points is 4. Duringtraining, the control points are transformed into 11 lane points forcal culating loss.

Does the above sentence mean training by 11 points and inference by 4 points? If that's what it means, how do you do it?

**Comment by wudongming97** [comment]
Because our lane head is bezier-based, it outputs 4 control points and transforms them into 11 lane points using a transformation matrix. Both training and testing are the same.

**Comment by Fightinging1997** [comment]
Thank you for your answer, but I still have some questions.
Where does transforms refer to here?

**Comment by wudongming97** [comment]
Please refer to this line:
https://github.com/wudongming97/TopoMLP/blob/master/projects/topomlp/models/heads/lane_head.py#L731

**Comment by Fightinging1997** [comment]
Thank you for your answer.
