### ISSUE TITLE
nstalling the environment

### ISSUE THREAD

**Issue by wangsiyu1410813** [wudongming97/TopoMLP#28]
There was a problem with mmdetection mmdetection3d mmcv when installing the environment. Can you provide a detailed version?

**Comment by wudongming97** [comment]
Please refer to https://github.com/wudongming97/TopoMLP/blob/master/docs/setup.md

**Comment by wangsiyu1410813** [comment]
What is the corresponding version of the dependent mmcv mmdetection2d mmdetection3d mmdet

**Comment by LJR-xpeng** [comment]
> Please refer to https://github.com/wudongming97/TopoMLP/blob/master/docs/setup.md

The mmdet3d is missing in the provided environment yaml file.

**Comment by wudongming97** [comment]
https://github.com/OpenDriveLab/OpenLane-V2/blob/master/docs/getting_started.md?plain=1#L71
