### ISSUE TITLE
The missing version of mmdet3d when installing the environment

### ISSUE THREAD

**Issue by LJR-xpeng** [wudongming97/TopoMLP#29]
What is the corresponding version of the dependent  mmdetection3d? It is missing in the provided environment yaml file.

**Comment by wudongming97** [comment]
https://github.com/OpenDriveLab/OpenLane-V2/blob/master/docs/getting_started.md?plain=1#L71

**Comment by LJR-xpeng** [comment]
> https://github.com/OpenDriveLab/OpenLane-V2/blob/master/docs/getting_started.md?plain=1#L71

Thanks!
