### ISSUE TITLE
Can you provide an environment configuration tutorial similar to TopoNet？That's very time saving and helpful, thanks~

### ISSUE THREAD

**Issue by DaiyiZhu** [wudongming97/TopoMLP#3]
![image](https://github.com/wudongming97/TopoMLP/assets/57313182/acbdca47-0e77-4ed2-8925-593df2a2f5f0)

**Comment by wudongming97** [comment]
@DaiyiZhu 
Wu follow [OpenLane-V2](https://github.com/OpenDriveLab/OpenLane-V2) for environment configuration.

**Comment by wudongming97** [comment]
@hello7623 
flash-attn=1.0.1
