### ISSUE TITLE
About YOLOv8

### ISSUE THREAD

**Issue by eeeric1** [wudongming97/TopoMLP#7]
Hello, thanks for your work.
In the paper, you mentioned that 'As an alternative, the high-quality proposals from YOLOv8 can serve as an anchor box initialization, providing better local priors.'
I want to understand how to use yolov8 results, I don't see yolov8 being used in the code.
Looking forward to your reply!

**Comment by wudongming97** [comment]
Hi, 
The YoloV8-based method has not been released yet. It needs some time to prepare the code.

**Comment by sugar-fly** [comment]
Hi, thank you for your work.

Is there a schedule for releasing the code of YoloV8-based method?
Looking forward to your rely!

best,
