### ISSUE TITLE
About topo heads

### ISSUE THREAD

**Issue by eeeric1** [wudongming97/TopoMLP#9]
Hi, thanks for your work.
I am a little confused about the topo head code, and I would like to ask you for advice.
In line 133 of topo_lt_head, targets need to be operated according to the shape of xs. I'm not quite sure why this is done. I understand that we can do the same thing as line 157 of topo_ll_head.
Looking forward to your reply!

**Comment by wudongming97** [comment]
Hi, 
It means computing the LT loss for only positive samples. It can increase the loss weights of positive samples (they are not too much in all samples).

**Comment by eeeric1** [comment]
Thanks for your reply!
I understand the purpose of this, but I'm not sure why topo_lt_head and topo_ll_head do it differently.
in topo_lt_head.py
```python3
if xs.size(0) != xs.size(1):
         targets = 1 - targets[0][xs_new].view(-1).long()
    else:
         targets = 1 - targets[0][xs_new][:, ys_new].view(-1).long()
```
in topo_ll_head.py
```python3
targets = 1 - targets[0][xs_new][:, ys_new].view(-1).long()
```

**Comment by wudongming97** [comment]
From my experience, the ll has more positive samples. Because each centerline has more than one connection, most centerlines may not connect any traffic element.

**Comment by eeeric1** [comment]
Hi, I'm still a bit confused about the code here
The main problem lies in this code
```python
if xs.size(0) != xs.size(1):
```
In my opinion, you can directly take targets[0][xs_new][:, ys_new], which is consistent with topo_ll_head, or in order to add some samples, take targets[0][xs_new].

**Comment by wudongming97** [comment]
Oh. Sorry for that. In our initial code, the ll and lt heads are not separated, so use this judgement.

**Comment by Wolfybox** [comment]
> Thanks for your reply! I understand the purpose of this, but I'm not sure why topo_lt_head and topo_ll_head do it differently. in topo_lt_head.py
> 
> ```python
> if xs.size(0) != xs.size(1):
>      targets = 1 - targets[0][xs_new].view(-1).long()
> else:
>      targets = 1 - targets[0][xs_new][:, ys_new].view(-1).long()
> ```
> 
> in topo_ll_head.py
> 
> ```python
> targets = 1 - targets[0][xs_new][:, ys_new].view(-1).long()
> ```

@wudongming97   I confused why there is a reverse operation here to make pos to 0 and neg to 1:

targets = 1 - targets[0][xs_new][:, ys_new].view(-1).long()
